name: 'publish'

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  publish-electron:
    outputs:
      appVersion: ${{ steps.extract-version.outputs.appVersion }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            artifact-name: ubuntu-x86_64
          - platform: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
            artifact-name: ubuntu-aarch64

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            ${{ startsWith(matrix.platform, 'ubuntu') && matrix.target || '' }}
            ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
            ${{ matrix.platform == 'windows-latest' && matrix.target == 'aarch64-pc-windows-msvc' && 'aarch64-pc-windows-msvc' || '' }}

      - name: install dependencies (ubuntu only)
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - name: install frontend dependencies
        run: pnpm install

      - name: Install rimraf
        run: pnpm add rimraf -D

      - name: Build Electron App
        run: pnpm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Artifacts for Linux
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          pnpm exec rimraf "dist/!(*.AppImage|*.yml|*.zip)"

      - name: Rename files with architecture suffix
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          # 进入dist目录
          cd dist
          
          # 为AppImage文件添加架构后缀
          for appimage in *.AppImage; do
            if [ -f "$appimage" ]; then
              mv "$appimage" "${appimage%.AppImage}-${{ matrix.arch-suffix }}.AppImage"
            fi
          done
          
          # 为yml文件添加架构后缀
          for yml in *.yml; do
            if [ -f "$yml" ]; then
              mv "$yml" "${yml%.yml}-${{ matrix.arch-suffix }}.yml"
            fi
          done
          
          # 为zip文件添加架构后缀（如果有）
          for zip in *.zip; do
            if [ -f "$zip" ]; then
              mv "$zip" "${zip%.zip}-${{ matrix.arch-suffix }}.zip"
            fi
          done

      - name: Extract version
        id: extract-version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION=${{ github.ref_name }}
          else
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "appVersion=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: upload artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ${{ matrix.artifact-name }}
          path: dist

  release:
    needs: publish-electron
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts  # 下载到artifacts目录，结构为artifacts/artifact-name/files

      - name: Prepare release files
        run: |
          # 创建dist目录
          mkdir -p dist
          
          # 为每个架构创建独立目录并复制文件，避免冲突
          for arch in $(ls artifacts); do
            mkdir -p "dist/$arch"
            cp -R "artifacts/$arch"/* "dist/$arch/"
          done

      - name: release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ needs.publish-electron.outputs.appVersion }}
          name: Release ${{ needs.publish-electron.outputs.appVersion }}
          files: "dist/**"  # 包含所有架构目录下的文件
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
